name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: maven

      - run: mvn package

      - uses: actions/cache/save@v3
        with:
          key: ${{ github.sha }}
          path: target

  publish-image:
    needs: build
    runs-on: ubuntu-latest
    environment: 'DEV'
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
      repo: ${{ env.repo }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache/restore@v3
        id: cache
        with:
          key: ${{ github.sha }}
          path: target

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''

      - run: echo repo=$(echo "${{github.repository}}" | tr 'A-Z' 'a-z') >>${GITHUB_ENV}

      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.repo }}:${{ steps.tag.outputs.new_tag }}

